"""empty message

Revision ID: 2f164520d36a
Revises: f75ea586ed5e
Create Date: 2023-12-03 19:10:40.338044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f164520d36a'
down_revision = 'f75ea586ed5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server', sa.String(), server_default='<infer api>', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.drop_column('server')

    # ### end Alembic commands ###
