"""empty message

Revision ID: 782a6cb895aa
Revises: f75ea586ed5e
Create Date: 2023-12-03 17:03:02.203246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782a6cb895aa'
down_revision = 'f75ea586ed5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial', schema=None) as batch_op:
        batch_op.drop_column('server')

    # ### end Alembic commands ###
